### ISSUE TITLE
Store query+channel logs in datastore

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/gircbnc#18]
I'm really interested in how exactly to handle this and store those messages. What sort of features will this message store be used by? IRCv3 stuff is throwing the idea of message searching / retrieval, arbitrary playback of messages and the like. Those seem to be useful features to implement with this sorta system backing it.

**Comment by prawnsalad** [comment]
With the ideas floating around and the features I've got in mind we would need to support the following:
* Store a message (bnc_user, time, type, from, to, body)
* Retrieve a group of messages based on multiple lookups:
  * Num messages after a time
  * Num messages before a time
* Search for a group of messages between a timeframe, returning X messages
* Searching must support a "search on this field" option since this is currently in the air for the ircv3 stuff.

Not all message datastores may support retrieval or searching so these may be optional. While we can add an option for searching on different fields, we can just default to "search everything" for the time being and add the new options in future as needed.

With all that said, a message datastore could implement the following interface:
~~~
.Store(userId, ircmsg)
.GetFromTime(userId, time, numMessages)
.GetBeforeTime(userId, time, numMessages)
.Search(userId, searchField, searchTerm, timeFrom, timeTo, numMessages)

.SupportsStore bool
.SupportsRetrieve bool
.SupportsSearch bool
~~~

For a quick .txt log datastore, only .Store could be implemented which just throws a structures message to disk.

**Comment by prawnsalad** [comment]
Note; Logging could be implemented using components to keep it logically separated from the core BNC functionality https://github.com/goshuirc/bnc/pull/19

**Comment by prawnsalad** [comment]
An interface is now in the logger component that allows multiple running message loggers each with different support:
* Storing logs
* Retrieving logs
* Searching logs
